apiVersion: v1
clusters:
- cluster:
    server: https://A5B7D77061F65755FDBC4290C6A991A5.gr7.us-east-1.eks.amazonaws.com:443
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJT3BLdzZWVVd6OUV3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TkRFd01qQXlNVFE0TVRWYUZ3MHpOREV3TVRneU1UVXpNVFZhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUNueGVvbFdLVjlWVU5CNWR1YmNtQmxEalhucHk5MklNZ25aV2RSc0s2MTZqV1ZrbHU1ZVhyK0FIVWEKeUx2bmZuZFIzWFlaSjZUcUs1ZHhFZkxZWVlUZDNJek5iL0FHa0xiN3gxTi9ON25EWGcwYk5hUXU2RGVPcWFBMgpRUHJLSTdFOUtNK2hhU3hFSy9GSksxRUNTWXBKamRWeWN2dWkvY2ZjaldNTGhDZXYySGE5VFdReHBFaTBSTkxvCmdXQ3RsZXFEMWlEMUxpdk84bElkNWU3dVNVR0YyMHJiZWZuam1vQUU4M016ZWdNTU9mbE4wdjEwV0pNUEFROEsKYUZubUdRSitPMG9MUXJNSHl5SVNabktFRHdYYWpSZ3dudGVPY0NMbUxQL1lReUdWUzQvRWsrZ3ZkWkZvRjZSeAp2UTBWVXBldjZSUG9HTmhZVUtKaE5hbWM3cjFwQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJTMHVrUmpFMnhNcTdKZ2YvWDJMSmFLS1RNZGFUQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQ005ZjZBUURhZgpiZGZCck1PR1VnYVhNQlNzbTNqbDRld25NTitwSnB2S0NQT2NYRW1IU3RoV3FwUVBsQlRTSk9qZ0JqOHpZbkRICkkrQjNHRkgyMUE5QjJzMFFRQkZ6N3A1akJnK2JRaEg2Z0M5ajkrWE91OGJkenJMSm9zL2FWeGd0YnhLRzgxb1oKT3pzT3o3d0gwOW5hTTlhY1pXS3c0d2JWRHZLRmxvK2traUJIS29WbXk5UXBKRGp2MnRBRTBZYWprUTdrYVA0dQp0RDFQc1EwdFhmdEttcXhrOVAxM1VTenNlL3dFSUt6WGFnVGROWVJkYVRGQlpjYXA2NlQrem1TNlB5S0xxNXY0CjIyQkFVQStkc3V3a2tQNnJWeUFEU2ptT1lyUGZ2akoxMklMYmVKcHpYemJmK1NwT0Q3NEk2R3ZQb1BKd1M5cXoKdjdEU25FM3BpRzljCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  name: arn:aws:eks:us-east-1:407048001844:cluster/Proyecto2
contexts:
- context:
    cluster: arn:aws:eks:us-east-1:407048001844:cluster/Proyecto2
    user: aws
  name: aws
current-context: aws
kind: Config
preferences: {}
users:
- name: aws
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      command: aws
      args:
        - eks
        - get-token
        - --cluster-name
        - Proyecto2