apiVersion: apps/v1
kind: Deployment
metadata:
  name: moodle
spec:
  replicas: 2
  selector:
    matchLabels:
      app: moodle
  template:
    metadata:
      labels:
        app: moodle
    spec:
      containers:
      - name: moodle
        image: bitnami/moodle:latest
        env:
        - name: MOODLE_DATABASE_HOST
          value: "54.210.152.123"
        - name: MOODLE_DATABASE_USER
          value: "moodleuser"
        - name: MOODLE_DATABASE_PASSWORD
          value: "moodlepass"
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: moodle-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: moodle